### ISSUE TITLE
Request; DXF File

### ISSUE THREAD

**Issue by NellyWhads** [clomie/ergodash-tilting-tenting-case#1]
Hello there,

I have tried converting the `.ai` file using some online converters and all of them have caused issues. Some drop a bunch of the vectors while others scale the image down so the units are all off.

Could we get a DXF exported image for this? I don't have AI license else I would submit a PR myself.

Cheers

**Comment by clomie** [comment]
Unfortunately I don't currently have AI licence...

**Comment by NellyWhads** [comment]
No worries, thanks
