### ISSUE TITLE
Design change results in needing 16x M2 -6mm hexagonal spacers.

### ISSUE THREAD

**Issue by clembo1** [clomie/ergodash-tilting-tenting-case#3]
When using the full size pcb.  this design calls for 16x m2 - 6mm hexagonal threaded spacers instead of 14x specified in the original ergodash guide.  Also found the same problem on the parts lists for the original guide when using both thumb keys for each side.  Not a big deal, just calling it out.  I also submitted an issue back on the original.

1. M2×6mm spacer. Should say "M2×6mm threaded spacer"
2. When using the full-size (i.e. both thumb cluster buttons), you need 16 spacers, not 14.
3. Need M2x5mm screws x26 instead of x22

**Comment by clomie** [comment]
Thanks for reporting.
The parts lists in this repository mentions additional parts only. I would leave it to the original guide.
